version: '3.1'

services:
  gt_mongo:
    build:
      context: ./
      dockerfile: Dockerfile
    command: mongod --config /etc/mongo/replica.yml
    volumes:
      - ./config/replica.yml:/etc/mongo/replica.yml
      - ./data:/data/db
      - ./backups:/backups
    ports:
      - 27017:27017
    extra_hosts:
      - "mongo1:195.216.218.230"
      - "mongo2:195.216.149.121"
      - "mongo3:195.216.164.34"
